pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/your-username/jenkinsCiCD.git'
            }
        }

        stage('Build & Test') {
            steps {
                sh './gradlew clean test'
            }
        }
    }
}
